### ISSUE TITLE
链接蓝牙报错

### ISSUE THREAD

**Issue by wc136706639** [kellysong/DeviceConnector#1]
2023-04-06 15:28:15.291 20213-20657/com.sjl.deviceconnector.test E/DEVICE_CONNECTOR: 蓝牙连接异常
    java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:772)
        at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:786)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:404)
        at com.sjl.deviceconnector.provider.BluetoothConnectProvider.open(BluetoothConnectProvider.java:85)
        at com.sjl.deviceconnector.test.activity.MainActivity$11.run(MainActivity.java:491)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by kellysong** [comment]
检查蓝牙地址，服务uuid,连接建议在子线程进行

**Comment by kellysong** [comment]
检查蓝牙地址，服务uuid,连接建议在子线程进行
